### ISSUE TITLE
Integrations: Zapier OAuth 2.0 integration fails

### ISSUE THREAD

**Issue by rishi-raj-jain** [polarsource/polar#6697]
### Description

> From [the ticket](https://app.plain.com/workspace/w_01JE9TRRX9KT61D8P2CH77XDQM/thread/th_01K3K14391S9FT2Q408YPYFWWC/)

The PolarxZapier OAuth flow is failing when attempting to authenticate users. This issue was discovered while using the Zapier's Polar integration.

### Current Behavior

Users are unable to complete the Polar OAuth process via Zapier. The authentication either stalls or returns an error message, preventing users from connecting their Polar accounts to Zapier.

### Expected Behavior

Users should be able to successfully complete the OAuth authentication flow with Zapier and connect their accounts without errors.

### Video

https://github.com/user-attachments/assets/190e3595-c9fb-4558-98f9-ccd7695d57b2

**Comment by frankie567** [comment]
Fixed!

**Comment by rishi-raj-jain** [comment]
@frankie567 

Can you share where was the fix made? As in on Zapier or in the Polar repo?

**Comment by rishi-raj-jain** [comment]
Unfortunately, this is not still fixed and I see the issue persist like the following:

<img width="1512" height="879" alt="Image" src="https://github.com/user-attachments/assets/95ec9e9a-3add-40ad-b677-f5f98d070dd6" />

**Comment by frankie567** [comment]
Sure!

So, basically the issue was introduced by this change: https://github.com/polarsource/polar/commit/59d164800572f6d2fdcd498ad53f41f8cc30fdfe It's a middleware that checks the validity of the bearer tokens passed in `Authorization`.

It turns out, strangely enough, that Zapier was adding a bearer token in `Authorization` when making a request to `/v1/oauth2/token`. I don't understand what was the purpose of that. The thing is, the middleware I mention above was triggered by that and returned a 401.

The solution was to tweak the Zapier integration to explicitly enforce a `null` `Authorization` header: https://github.com/polarsource/polar-zapier/commit/d952f2c917c65f3519592741b3e1359eb288c5f4

**Comment by frankie567** [comment]
> Unfortunately, this is not still fixed and I see the issue persist like the following:
> 
> <img alt="Image" width="1512" height="879" src="https://private-user-images.githubusercontent.com/46300090/487220394-95ec9e9a-3add-40ad-b677-f5f98d070dd6.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc0MTE5ODYsIm5iZiI6MTc1NzQxMTY4NiwicGF0aCI6Ii80NjMwMDA5MC80ODcyMjAzOTQtOTVlYzllOWEtM2FkZC00MGFkLWI2NzctZjVmOThkMDcwZGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA5VDA5NTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMmQ5MjQ5OTc4NDFhNDU3ZTQ0YjBlZTUzNjFhYWUwNDZjMzJjMzhlMDI5YTljMWJlZDBmZDkwMTRkM2Y2ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rncAM-Kh4qSYRdPXA6x57zoDOf6IYVjcSo-hnSDjZBI">

Can you try again? I think this is just a temporary quirk from Zapier. Checked again right now and it works.

**Comment by rishi-raj-jain** [comment]
Just tried again:
<img width="1512" height="387" alt="Image" src="https://github.com/user-attachments/assets/08b49574-f236-4a96-b650-3b1bc4e6a69b" />

**Comment by rishi-raj-jain** [comment]
It worked! The issue is of 1.0.3 and not with 1.0.4. Given that I already had `Polar 1.0.3` being set in my Zapier account (at the time I used it) it was defaulting to the old behavior.
