### ISSUE TITLE
Type error: The inferred type of 'authClient' cannot be named...

### ISSUE THREAD

**Issue by mezotv** [polarsource/polar#7956]
### Description (tl;dr)

Types of the @polar-sh/better-auth seem to be messed up making builds fail.

### What is the expected behaviour?

The code builds without throwing an error

### What errors or issues are you experiencing?

Bumped better auth from  1.3.8 to  1.3.34 and wanted to bump the polar plugin too. We are currently on v1.1.0 and wanted to bump to 1.4.0 but that results in the following error

```bash
Type error: The inferred type of 'authClient' cannot be named without a reference to '.pnpm/@polar-sh+checkout@0.1.14_@stripe+react-stripe-js@4.0.2_@stripe+stripe-js@7.9.0_react-dom@19._ap4ilzmxjdxstcsltxdazqpy2m/node_modules/@polar-sh/checkout/embed'. This is likely not portable. A type annotation is necessary.
```

This has likely been broken for previous versions too since I also tried it with 1.3.0 and ran into the same type error

### How can it be reproduced?

Bump to the latest version of better auth (1.3.34) and @polar-sh/better-auth (1.4.0) in a nextjs app (16.0.3 in our case) and run a build either locally or on vercel.

Here is the code I use for testing
```ts
import { toast } from "@marble/ui/components/sonner";
import { polarClient } from "@polar-sh/better-auth";
import {
  emailOTPClient,
  inferOrgAdditionalFields,
  organizationClient,
} from "better-auth/client/plugins";
import { createAuthClient } from "better-auth/react";
import type { auth } from "./auth";

export const authClient = createAuthClient({
  baseURL: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  plugins: [
    organizationClient({ schema: inferOrgAdditionalFields<typeof auth>() }),
    emailOTPClient(),
    polarClient(),
  ],
  fetchOptions: {
    onError(e) {
      if (e.error.status === 429) {
        toast.error("Too many requests. Please try again later.");
      }
    },
  },
});

export const {
  signUp,
  signIn,
  signOut,
  useSession,
  organization,
  useListOrganizations,
  useActiveOrganization,
  emailOtp,
  checkout,
} = authClient;
```

### Which adapter(s) does this relate to?

- [x] Next.js
- [x] BetterAuth
- [ ] Nuxt
- [ ] Remix
- [ ] TanStack Start
- [ ] SvelteKit
- [ ] Supabase
- [ ] Astro
- [ ] Deno
- [ ] Elysia
- [ ] Express
- [ ] Fastify
- [ ] Hono
- [ ] Others (please specify in the description)

### What environment are you running it in?

Vercel and local deployments on a macbook

**Comment by emilwidlund** [comment]
Just tested this locally, and our adapter works fine with BetterAuth ´1.3.34´

**Comment by mezotv** [comment]
> Just tested this locally, and our adapter works fine with BetterAuth ´1.3.34´

Any idea why this isnt working for us on Vercel then?

**Comment by emilwidlund** [comment]
@mezotv Alright, I think I found an issue. I've published `@polar-sh/better-auth@1.5.0` now. Please make sure to update the Polar SDK to `0.41.5` too.

**Comment by mezotv** [comment]
> [@mezotv](https://github.com/mezotv) Alright, I think I found an issue. I've published `@polar-sh/better-auth@1.5.0` now. Please make sure to update the Polar SDK to `0.41.5` too.

Tried that and unfortunately getting the same error, might have something to do with it being in a monorepo? I can try to setup a minimal repo for reproduction later! Here is our current repo/pr https://github.com/usemarble/marble/pull/253

**Comment by mezotv** [comment]
Hey @emilwidlund better-auth 1.4.0 just dropped do you think you could bump the version used in @polar-sh/better-auth to that? Just to see if that fixes anything.

**Comment by pieterbeulque** [comment]
We released a 1.6.0 build that has a separate `@polar-sh/better-auth/client` export to work around this (h/t @rishi-raj-jain). While the true fix lays with Better Auth upstream, this should allow you to work around it.

The minimum Better Auth version is also updated to 1.4.x in the new version.

**Comment by mezotv** [comment]
> We released a 1.6.0 build that has a separate `@polar-sh/better-auth/client` export to work around this (h/t [@rishi-raj-jain](https://github.com/rishi-raj-jain)). While the true fix lays with Better Auth upstream, this should allow you to work around it.

Hey Pieter, I just try and this does not seem to fix the issue. I pinged beka and asked if he could take a look so hopefully it can be fixed upstream. Thanks for your help!

**Comment by rishi-raj-jain** [comment]
@mezotv 

Can you share the minimal reproduction?

**Comment by mezotv** [comment]
> Can you share the minimal reproduction?

Sure let me create one today!

**Comment by rishi-raj-jain** [comment]
Thank you!

**Comment by pieterbeulque** [comment]
Hey @mezotv, the issue you mention in [better-auth/better-auth#4250](https://github.com/better-auth/better-auth/issues/4250) is not related to this issue.

If you have a repro we can help figure out what's going on there, it might be something you can fix by deduping some dependencies or we may have to untangle something with our nested `@polar-sh/checkout` dependency. Let me know 😊 thanks.

**Comment by mezotv** [comment]
> Hey [@mezotv](https://github.com/mezotv), the issue you mention in [better-auth/better-auth#4250](https://github.com/better-auth/better-auth/issues/4250) is not related to this issue.

Good to know thanks!

> If you have a repro we can help figure out what's going on there, it might be something you can fix by deduping some dependencies or we may have to untangle something with our nested `@polar-sh/checkout` dependency. Let me know 😊 thanks.

I just created a minimal reproduction repo https://github.com/mezotv/polar-better-auth-repro. I hope this helps it shows the exact same error! 

<img width="753" height="159" alt="Image" src="https://github.com/user-attachments/assets/624307ee-b898-4865-b0c1-da1eac008416" />

**Comment by pieterbeulque** [comment]
Fixed in 1.6.1, sorry about that!

**Comment by mezotv** [comment]
> Fixed in 1.6.1, sorry about that!

Hey Pieter, super sorry to be that guy but now we are running into another issue. Want me to create a new issue on GitHub?

It might only be switching undefined for null 

<img width="737" height="89" alt="Image" src="https://github.com/user-attachments/assets/ebdeed46-48c8-4ca5-9cc1-e0d35b3b9bf7" />

**Comment by pieterbeulque** [comment]
Make sure your Better Auth is on 1.6.4, they recently changed that type from `GenericEndpointContext | undefined` to`GenericEndpointContext | null` so we had to follow.

**Comment by mezotv** [comment]
> Make sure your Better Auth is on 1.6.4, they recently changed that type from `GenericEndpointContext | undefined` to`GenericEndpointContext | null` so we had to follow.

Unfortunately my better-auth is on 1.4.6, maybe they changed it back?

**Comment by pieterbeulque** [comment]
Try re-installing or upgrading your dependencies, I'm pretty sure it's something with your dependencies. See👇 

https://github.com/better-auth/better-auth/blob/a10a467e14af9817fa66a2ec753f2db383d32f4a/packages/core/src/types/init-options.ts#L998

**Comment by mezotv** [comment]
Oh yea seems to work locally now, still getting some issues on Vercel deployments but ill figure that out myself. Thanks for the help!

Edit: Got the deployment issue fixed too, works now thanks!
