### ISSUE TITLE
polarClient import breaks Next.js 16 Turbopack: node:async_hooks not available in browser

### ISSUE THREAD

**Issue by naodya** [polarsource/polar#8251]
### Description (tl;dr)

`polarClient` from `@polar-sh/better-auth` crashes in Next.js 16 with Turbopack because the package bundles server-only code that imports `node:async_hooks`.

### What is the expected behaviour?

`polarClient` should be importable in browser environments without pulling in server-only dependencies like `node:async_hooks`.

### What errors or issues are you experiencing?

```
Failed to fetch dynamically imported module: node:async_hooks
```

Console warnings:
```
[better-auth] Warning: AsyncLocalStorage is not available in this environment. Some features may not work as expected.
```

The root cause is that `@polar-sh/better-auth` bundles all exports into a single `index.js` with server imports at the top:

```javascript
// dist/index.js - these run even when only importing polarClient
import { APIError } from "better-auth/api";
import { sessionMiddleware } from "better-auth/api";
import { createAuthEndpoint } from "better-auth/plugins";
```

These imports eventually reach `node:async_hooks` via `@better-auth/core`, which doesn't exist in browsers.

### How can it be reproduced?

1. Create a Next.js 16 app (Turbopack is the default bundler)
2. Install `@polar-sh/better-auth@1.5.0` and `better-auth@1.4.5`
3. Create a client auth file:

```typescript
// lib/auth-client.ts
import { polarClient } from "@polar-sh/better-auth";
import { createAuthClient } from "better-auth/react";

export const authClient = createAuthClient({
  plugins: [polarClient()],
});
```

4. Import `authClient` in any client component
5. Run `next dev` and navigate to that page

### Which adapter(s) does this relate to?

- [x] BetterAuth
- [x] Next.js

### What environment are you running it in?

- Next.js 16.0.0 with Turbopack (default bundler)
- `@polar-sh/better-auth`: 1.5.0
- `better-auth`: 1.4.5
- Local development (also affects Vercel deployments)

### Proposed Solution

Split the package into separate entry points:

```json
{
  "exports": {
    ".": "./dist/index.js",
    "./client": "./dist/client.js"
  }
}
```

This would allow:
```typescript
import { polarClient } from "@polar-sh/better-auth/client";  // Browser-safe
import { polar, checkout } from "@polar-sh/better-auth";      // Server-only
```

### Current Workaround

Create a local `polarClient` that imports directly from `@polar-sh/checkout/embed`:

```typescript
import { PolarEmbedCheckout } from "@polar-sh/checkout/embed";

export const polarClient = () => ({
  id: "polar-client",
  $InferServerPlugin: {},
  getActions: ($fetch) => ({
    checkoutEmbed: async (data) => {
      const res = await $fetch("/checkout", {
        method: "POST",
        body: { ...data, redirect: false, embedOrigin: window.location.origin },
      });
      if (res.error) throw new Error(res.error.message);
      const theme = new URL(res.data.url).searchParams.get("theme") ?? "light";
      return await PolarEmbedCheckout.create(res.data.url, theme);
    },
  }),
});
```

### Related Issues

- https://github.com/better-auth/better-auth/issues/6024
- https://github.com/polarsource/polar-adapters/issues/195 (tree-shaking)

**Comment by landoncolburn** [comment]
Fixed in canary

**Comment by pieterbeulque** [comment]
That workaround is fine, issue will be fixed upstream in Better Auth in 1.4.6. Thanks @landoncolburn.

Let's follow up in #8166

**Comment by aleksa-codes** [comment]
I am still getting error like this: https://github.com/better-auth/better-auth/issues/5539#issuecomment-3616529487 even on 1.4.6.

```
$ bun run build
$ next build
   ▲ Next.js 16.0.10 (Turbopack)
   - Environments: .env

   Creating an optimized production build ...

> Build error occurred
Error: Turbopack build failed with 1 errors:
./node_modules/@polar-sh/better-auth/dist/chunk-5QR5Y5PS.js
Code generation for chunk item errored
An error occurred while generating the chunk item [project]/node_modules/@polar-sh/better-auth/dist/chunk-5QR5Y5PS.js [app-client] (ecmascript)

Caused by:
- the chunking context (unknown) does not support external modules (request: node:module)

Debug info:
- An error occurred while generating the chunk item [project]/node_modules/@polar-sh/better-auth/dist/chunk-5QR5Y5PS.js [app-client] (ecmascript)
- Execution of <MergedEcmascriptModuleChunkItem as EcmascriptChunkItem>::content_with_async_module_info failed
- Execution of *EcmascriptChunkItemContent::new failed
- Execution of EcmascriptModuleContent::new_merged failed
- the chunking context (unknown) does not support external modules (request: node:module)
```

edit:
switching from:
```ts
import { polarClient } from "@polar-sh/better-auth";
```
to
```ts
import { polarClient } from "@polar-sh/better-auth/client"
```

Solved it for me. Both Polar and Better Auth docs still say to use `"@polar-sh/better-auth"` tho
